### PR TITLE
Update podman-rest.sh

### PR DESCRIPTION
**Pull request by RishiMahavar**
updated port number

### CODE REVIEW

**Comment by RishiMahavar** [comment]
Please update the given port number

**Review by scriptkkiddie — COMMENTED** [review]
Hi @RishiMahavar, I'm just reviewing your PR!

**Comment by RishiMahavar** [comment]
Please do it ASAP !

**Comment by scriptkkiddie** [comment]
> updated port number

Hi @RishiMahavar, I've reviewed your PR, and approving it now!

**Review by scriptkkiddie — APPROVED** [review]

**Pull request merged**
